# Generated by Django 4.2.5 on 2023-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lessonviewhistory_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonviewhistory',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
